//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notepad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notepad.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the app.
        /// </summary>
        public static string AccessibleDescriptionClose {
            get {
                return ResourceManager.GetString("AccessibleDescriptionClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows more options File related.
        /// </summary>
        public static string AccessibleDescriptionMenuFile {
            get {
                return ResourceManager.GetString("AccessibleDescriptionMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new tab.
        /// </summary>
        public static string AccessibleDescriptionMenuNew {
            get {
                return ResourceManager.GetString("AccessibleDescriptionMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new tab with an existing File.
        /// </summary>
        public static string AccessibleDescriptionMenuOpen {
            get {
                return ResourceManager.GetString("AccessibleDescriptionMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An options menu strip.
        /// </summary>
        public static string AccessibleDescriptionMenuStrip {
            get {
                return ResourceManager.GetString("AccessibleDescriptionMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a notepad app, that can handle multiple tabs for file editing.
        /// </summary>
        public static string AccessibleDescriptionProgram {
            get {
                return ResourceManager.GetString("AccessibleDescriptionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close app.
        /// </summary>
        public static string AccessibleNameClose {
            get {
                return ResourceManager.GetString("AccessibleNameClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File options.
        /// </summary>
        public static string AccessibleNameMenuFile {
            get {
                return ResourceManager.GetString("AccessibleNameMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        public static string AccessibleNameMenuNew {
            get {
                return ResourceManager.GetString("AccessibleNameMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string AccessibleNameMenuOpen {
            get {
                return ResourceManager.GetString("AccessibleNameMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options menu.
        /// </summary>
        public static string AccessibleNameMenuStrip {
            get {
                return ResourceManager.GetString("AccessibleNameMenuStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notepad.
        /// </summary>
        public static string AccessibleNameProgram {
            get {
                return ResourceManager.GetString("AccessibleNameProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string MenuHowToUse {
            get {
                return ResourceManager.GetString("MenuHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string TabNew {
            get {
                return ResourceManager.GetString("TabNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! This was made just as a passion personal little project 😊. You can see any updates on https://github.com/Hashimini/Notepad. And some instructions at the usage section..
        /// </summary>
        public static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its very simple. You can start writing and then go on File -&gt; Save, then you choose where to save and what name. You can also go on File -&gt; Open to load an already written File!..
        /// </summary>
        public static string TextHowToUse {
            get {
                return ResourceManager.GetString("TextHowToUse", resourceCulture);
            }
        }
    }
}
